Add suport for SPM
MateeDevs/MluviiIOSLibrary pull request #1
Opened 2022-01-26 10:56 UTC by tomas-bat

# :pencil: Description
- This PR updates the framework and adds support for Swift Package Manager.

# :bulb: What’s new?
- Added `Package.swift`

2022-01-27 05:46 UTC, tommassbrand requested changes

2022-01-27 05:46 UTC, tommassbrand commented on MluviiChat/MluviiChat/MluviiChatLibrary.swift
> +    public func createWebView(url:String, companyGuid:String, tenantId:String, presetName:String?, language:String?, scope:String?) -> WKWebView {
Format :) add whitespace

2022-01-27 05:46 UTC, tommassbrand commented on MluviiChat/MluviiChat/MluviiChatLibrary.swift
>           if(presetName != nil){
Format the lines :)

2022-01-27 05:46 UTC, tommassbrand commented on MluviiChat/MluviiChat/MluviiChatLibrary.swift
> +        }
Format the lines and conditions :)

2022-01-27 07:23 UTC, tomas-bat commented
@tommassbrand You commented on code from Mluvii's library, do we want to edit that?

2022-01-28 06:54 UTC, tommassbrand commented
Oh okay, then let it be :) @tomas-bat

2022-01-30 16:27 UTC, pchmelar requested changes
- I don't know why this PR shows changes in some files, that remain unchanged (like MluviiChat.podspec etc). 🤔 Probably something with how forks work on GitHub.
- `.DS_Store` and `xcuserdata` shouldn't be a part of the repo, please remove them and add them to `.gitignore` (you can copy-paste `.gitignore` from our DevStack repo) 
- Did you take a look at that SwiftUI version of this library? 🙂

2022-01-31 07:50 UTC, tomas-bat commented
- Removed `.DS_Store` and `xcuserdata` directory. It is still showing on of the files in this directory as edited, not deleted (not sure why, guess it's because it was also changed), but that file is not in this branch anymore.
- I did not look into the SwiftUI version very much, I just wanted to update it, add the SPM support, so we can use it as is. Should I create another task as part of the refactor, that looks into whether it can be replaced with the SwiftUI version? @pchmelar

2022-01-31 13:50 UTC, pchmelar commented
Yeah, please create a low-priority task for testing the SwiftUI version 🙂

2022-01-31 13:50 UTC, pchmelar approved these changes

2022-01-31 14:03 UTC, tomas-bat commented
> Yeah, please create a low-priority task for testing the SwiftUI version 🙂

Created the task [here](https://mateedevs.atlassian.net/jira/software/projects/UP/boards/1/backlog?selectedIssue=UP-650).

2022-01-31 14:04 UTC, merged